collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.060538343619555235
  brandStrength: 0.3517024302855134
  lightness: 0.2814263254404068
  brandColors:
    - '#6B0C22'
    - '#D9042B'
    - '#F4CB89'
    - '#588C8C'
    - '#011C26'
  rhythmicContrast: 0.4624707279726863
typography_spectrum: 0.485270997043699
navigation:
  - id: 'http://www.milanart.work'
    url: 'http://www.milanart.work'
    name: About
    type: external
  - id: 'https://www.instagram.com/johnandellimilan/'
    url: 'https://www.instagram.com/johnandellimilan/'
    name: Instagram
    type: external
  - id: 'https://www.facebook.com/Milan-910719832357615/'
    url: 'https://www.facebook.com/Milan-910719832357615/'
    name: Facebook
    type: external
layout_spectrum: 0.41339622414670885
name: John and Elli Milan
