collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.08968847
color:
  saturation: 0.8125672
  brandStrength: 0.8920515
  lightness: 0.754565
  brandColors:
    - '#F8EED3'
    - '#0F0E0A'
    - '#2FB6B9'
    - '#CA6A37'
    - '#C01114'
  rhythmicContrast: 0.7137486
navigation:
  - id: 'http://www.milanart.work'
    url: 'http://www.milanart.work'
    name: About
    type: external
  - id: 'https://www.instagram.com/johnandellimilan/'
    url: 'https://www.instagram.com/johnandellimilan/'
    name: Instagram
    type: external
  - id: 'https://www.facebook.com/Milan-910719832357615/'
    url: 'https://www.facebook.com/Milan-910719832357615/'
    name: Facebook
    type: external
layout_spectrum: 0.2497315
name: John and Elli Milan
