typography_spectrum: 0.8888292
color:
  saturation: 0.06053834361955523
  brandStrength: 0.3517024302855134
  rhythmicContrast: 0.4624707279726863
  brandColors:
    - '#6B0C22'
    - '#D9042B'
    - '#F4CB89'
    - '#588C8C'
    - '#011C26'
  lightness: 0.2814263254404068
layout_spectrum: 0.2303974
name: John and Elli Milan
navigation:
  - name: About
    url: 'http://www.milanart.work'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/johnandellimilan/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/Milan-910719832357615/'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Art Renaissance Wave
description: 'Shine Your Art, Change The World'
