title: 'The Art Renaissance '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: 'Shine Your Art, Change The World'
color:
  saturation: 0.2690655
  brandStrength: 1
  lightness: 0.5204082
  brandColors:
    - '#6B0C22'
    - '#D9042B'
    - '#F4CB89'
    - '#588C8C'
    - '#011C26'
  rhythmicContrast: 0.4624707
navigation:
  - name: About
    url: 'http://www.milanart.work'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/johnandellimilanart/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/Milan-910719832357615/'
    type: external
  - name: Artwork
    id: 0bb188fa-189a-4e95-b7e2-d9279ba69719
    type: content
name: John and Elli Milan
author:
  name: John Milan
  email: johnmilan42@yahoo.com
logo: null
typography_spectrum: 0.452739
layout_spectrum: 0.09613316
