layout_spectrum: 0.864470346365124
typography_spectrum: 0.2650086195208132
color:
  brandStrength: 0.176828951574862
  lightness: 0.11673155380412936
  saturation: 0.6858025374822319
  rhythmicContrast: 0.8441196794155985
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: John and Elli Milan
navigation:
  - id: 'http://www.milanart.work'
    url: 'http://www.milanart.work'
    name: About
    type: external
  - id: 'https://www.instagram.com/johnandellimilan/'
    url: 'https://www.instagram.com/johnandellimilan/'
    name: Instagram
    type: external
