collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6933405
  brandStrength: 1
  lightness: 0.7320086
  brandColors:
    - '#0B0601'
    - '#C8A472'
    - '#CFCDB4'
    - '#A9864F'
    - '#5D3C10'
  rhythmicContrast: 0.5354457
typography_spectrum: 1
navigation:
  - id: 'http://www.milanart.work'
    url: 'http://www.milanart.work'
    name: About
    type: external
  - id: 'https://www.instagram.com/johnandellimilan/'
    url: 'https://www.instagram.com/johnandellimilan/'
    name: Instagram
    type: external
  - id: 'https://www.facebook.com/Milan-910719832357615/'
    url: 'https://www.facebook.com/Milan-910719832357615/'
    name: Facebook
    type: external
layout_spectrum: 0.7062299
name: John and Elli Milan
