title: 'The Art Renaissance '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2690655
  brandStrength: 0.0005370569
  lightness: 0.5204082
  brandColors:
    - '#6B0C22'
    - '#D9042B'
    - '#F4CB89'
    - '#588C8C'
    - '#011C26'
  rhythmicContrast: 0.4624707
typography_spectrum: 0.452739
description: 'Shine Your Art, Change The World'
navigation:
  - name: About
    url: 'http://www.milanart.work'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/johnandellimilan/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/Milan-910719832357615/'
    type: external
layout_spectrum: 0.09613316
name: John and Elli Milan
